from abc import ABC, abstractmethod
import torch
import torch.nn as nn
from ..ebm import EBM

class Regularizer(nn.Module, ABC):
    """
    Abstract base class for all regularizers.
    It inherits from nn.Module so that regularizers can have their own
    parameters and be properly managed by PyTorch and PyTorch Lightning.
    """
    def __init__(self, config: dict):
        """
        Args:
            config (dict): A dictionary of configuration parameters for the regularizer.
        """
        super().__init__() # Initialize the nn.Module part
        self.config = config

    @abstractmethod
    def calculate_loss(self, ebm_model: EBM, positive_samples: torch.Tensor, negative_samples: torch.Tensor) -> torch.Tensor:
        """
        Calculates the regularization loss.

        Args:
            ebm_model (EBM): The EBM model.
            positive_samples (torch.Tensor): Samples from the data distribution.
            negative_samples (torch.Tensor): Samples generated by the sampler.

        Returns:
            torch.Tensor: The scalar regularization loss.
        """
        pass
