import torch
from typing import Dict

from .base_regularizer import Regularizer
from ..ebm import EBM

class L2EnergyRegularizer(Regularizer):
    """
    Applies L2 regularization on the energy values to prevent them from
    growing too large. The loss is calculated as lambda_e * E(x)^2, applied
    to both positive and negative samples. This encourages the model to learn
    an energy surface that is centered around zero.
    """
    def __init__(self, config: Dict):
        """
        Initializes the L2EnergyRegularizer.

        Args:
            config (Dict): A dictionary containing configuration parameters.
                - lambda_e (float): The regularization strength.
        """
        super().__init__(config)
        self.lambda_e = config.get('lambda_e', 0.1)

    def calculate_loss(self, ebm_model: EBM, positive_samples: torch.Tensor, negative_samples: torch.Tensor) -> torch.Tensor:
        """
        Calculates the L2 energy regularization loss for both positive and negative samples.

        Args:
            ebm_model (EBM): The EBM model.
            positive_samples (torch.Tensor): Samples from the data distribution.
            negative_samples (torch.Tensor): Samples generated by the sampler.

        Returns:
            torch.Tensor: The scalar regularization loss.
        """
        # Get energies for both positive and negative samples
        positive_energy = ebm_model(positive_samples)
        negative_energy = ebm_model(negative_samples)

        # Calculate L2 penalty on the energies.
        # We take the mean of the squared energies across the batch.
        l2_penalty = (positive_energy**2).mean() + (negative_energy**2).mean()

        return self.lambda_e * l2_penalty
