import torch
from typing import Dict

from .base_regularizer import Regularizer
from ..ebm import EBM

class GradientPenaltyRegularizer(Regularizer):
    """
    Applies a gradient penalty to the EBM, encouraging the norm of the energy
    function's gradient to be close to a target value (typically 1). This is a
    form of Lipschitz regularization, which can improve training stability.
    The penalty is calculated on samples interpolated between positive (real)
    and negative (generated) samples.
    """
    def __init__(self, config: Dict):
        """
        Initializes the GradientPenaltyRegularizer.

        Args:
            config (Dict): A dictionary containing configuration parameters.
                - lambda_gp (float): The regularization strength.
                - target (float): The target value for the gradient norm (usually 1.0).
        """
        super().__init__(config)
        self.lambda_gp = config.get('lambda_gp', 1.0)
        self.target = config.get('target', 1.0)

    def calculate_loss(self, ebm_model: EBM, positive_samples: torch.Tensor, negative_samples: torch.Tensor) -> torch.Tensor:
        """
        Calculates the gradient penalty loss.

        Args:
            ebm_model (EBM): The EBM model.
            positive_samples (torch.Tensor): Samples from the data distribution.
            negative_samples (torch.Tensor): Samples generated by the sampler.

        Returns:
            torch.Tensor: The scalar regularization loss.
        """
        # Create random weights for interpolation
        alpha_shape = [positive_samples.shape[0]] + [1] * (positive_samples.dim() - 1)
        alpha = torch.rand(alpha_shape, device=positive_samples.device)

        # Interpolate between positive and negative samples
        interpolated_samples = alpha * positive_samples.detach() + (1 - alpha) * negative_samples.detach()
        interpolated_samples.requires_grad_(True)

        # Calculate energy for the interpolated samples
        energy_interpolated = ebm_model(interpolated_samples)

        # Calculate gradients of the energy with respect to the interpolated samples.
        # create_graph=True is crucial because we penalize the gradient itself, so the
        # regularization loss needs to flow back to the model parameters.
        grad, = torch.autograd.grad(
            outputs=energy_interpolated.sum(),
            inputs=interpolated_samples,
            create_graph=True,
            retain_graph=True, # Good practice when using create_graph
        )

        # Reshape gradient to (batch_size, -1) to compute the norm for each sample
        grad = grad.view(grad.shape[0], -1)
        # Add a small epsilon for numerical stability in case of zero gradient
        grad_norm = torch.sqrt(torch.sum(grad**2, dim=1) + 1e-8)

        # Calculate the penalty: mean of (||grad|| - target)^2
        penalty = ((grad_norm - self.target)**2).mean()

        return self.lambda_gp * penalty

    @staticmethod
    def get_hyperparameter_info() -> dict:
        return {
            "lambda_gp": {
                "description": "Weight of the gradient penalty.",
                "recommended": "1.0 to 10.0",
                "type": "float"
            },
            "target": {
                "description": "The target value for the gradient norm.",
                "recommended": "1.0",
                "type": "float"
            }
        }
